# Generated by Django 5.2.13 on 2026-04-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('extra_schema', models.JSONField(blank=True, help_text='JSON Schema for validating extra_data on ContentItem', null=True)),
                ('template_name', models.CharField(blank=True, help_text='Template path for detail view, e.g. content/data_format_detail.html', max_length=120)),
                ('icon_slug', models.SlugField(blank=True, max_length=60)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'db_table': 'content_type_def',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('body_md', models.TextField(blank=True, help_text='Markdown body')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published'), ('deprecated', 'Deprecated')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered users'), ('admin', 'Admin only')], default='public', max_length=20)),
                ('reproducibility', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='content.contenttypedef')),
            ],
            options={
                'db_table': 'content_item',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.contentitem')),
            ],
            options={
                'db_table': 'revision_log',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('source_type', models.CharField(blank=True, choices=[('official_spec', 'Official Specification'), ('official_docs', 'Official Documentation'), ('paper', 'Paper'), ('repository', 'Repository'), ('policy', 'Policy'), ('tutorial', 'Tutorial'), ('community_note', 'Community Note')], max_length=40)),
                ('publisher', models.TextField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('version_label', models.CharField(blank=True, max_length=80)),
                ('license', models.TextField(blank=True)),
                ('citation_text', models.TextField(blank=True)),
                ('identifier_type', models.CharField(blank=True, choices=[('DOI', 'DOI'), ('URL', 'URL'), ('RRID', 'RRID'), ('Accession', 'Accession'), ('ISBN', 'ISBN'), ('arXiv', 'arXiv'), ('other', 'Other')], max_length=20)),
                ('identifier_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_reference',
                'indexes': [models.Index(fields=['source_type'], name='idx_sr_type'), models.Index(fields=['identifier_type', 'identifier_value'], name='idx_sr_doi')],
            },
        ),
        migrations.CreateModel(
            name='ContentSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_role', models.CharField(choices=[('primary_spec', 'Primary Specification'), ('documentation', 'Documentation'), ('paper', 'Paper'), ('tutorial', 'Tutorial'), ('example', 'Example'), ('related', 'Related')], default='related', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='content.contentitem')),
                ('source_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='content_links', to='content.sourcereference')),
            ],
            options={
                'db_table': 'content_source_link',
            },
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(choices=[('related_to', 'Related to'), ('supported_by', 'Supported by'), ('reads', 'Reads'), ('writes', 'Writes'), ('uses', 'Uses'), ('input_format', 'Input format'), ('output_format', 'Output format'), ('source_repository', 'Source repository'), ('converts_to', 'Converts to'), ('supersedes', 'Supersedes'), ('requires', 'Requires'), ('example_of', 'Example of')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='content.contentitem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='content.contentitem')),
            ],
            options={
                'db_table': 'content_relation',
                'indexes': [models.Index(fields=['from_item'], name='idx_cr_from'), models.Index(fields=['to_item'], name='idx_cr_to'), models.Index(fields=['rel_type'], name='idx_cr_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_item', models.F('to_item')), _negated=True), name='no_self_relation')],
                'unique_together': {('from_item', 'to_item', 'rel_type')},
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'visibility'], name='idx_ci_status_vis'),
        ),
        migrations.AddIndex(
            model_name='revisionlog',
            index=models.Index(fields=['content_item'], name='idx_rl_item'),
        ),
        migrations.AlterUniqueTogether(
            name='revisionlog',
            unique_together={('content_item', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='contentsourcelink',
            index=models.Index(fields=['content_item'], name='idx_csl_item'),
        ),
        migrations.AddIndex(
            model_name='contentsourcelink',
            index=models.Index(fields=['source_ref'], name='idx_csl_ref'),
        ),
        migrations.AlterUniqueTogether(
            name='contentsourcelink',
            unique_together={('content_item', 'source_ref', 'link_role')},
        ),
    ]
