# Generated by Django 5.2.13 on 2026-04-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('comment_type', models.CharField(choices=[('general', 'General note'), ('correction', 'Correction'), ('tip', 'Tip'), ('question', 'Question')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged'), ('hidden', 'Hidden')], default='visible', max_length=20)),
                ('section_anchor', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.contentitem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='comments.contentcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_comment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_item', 'status'], name='idx_cc_item'), models.Index(fields=['user'], name='idx_cc_user'), models.Index(fields=['parent'], name='idx_cc_parent'), models.Index(fields=['comment_type'], name='idx_cc_type')],
            },
        ),
    ]
