# Generated by Django 5.2.13 on 2026-04-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source_type', models.CharField(blank=True, max_length=40)),
                ('sync_strategy', models.CharField(choices=[('manual', 'Manual'), ('periodic', 'Periodic'), ('webhook', 'Webhook')], default='manual', max_length=20)),
                ('sync_url', models.URLField(blank=True, max_length=2000)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('failed', 'Failed'), ('stale', 'Stale'), ('skipped', 'Skipped')], max_length=20)),
                ('raw_metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='content.contentitem')),
            ],
            options={
                'db_table': 'data_source_sync',
                'indexes': [models.Index(fields=['content_item'], name='idx_dss_item'), models.Index(fields=['sync_status'], name='idx_dss_status')],
            },
        ),
    ]
