# Generated by Django 5.2.13 on 2026-04-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('domain', 'Domain'), ('format', 'Format'), ('language', 'Language'), ('skill', 'Skill Level'), ('topic', 'Topic'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.tag')),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='content.contentitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='taxonomy.tag')),
            ],
            options={
                'db_table': 'content_tag',
                'indexes': [models.Index(fields=['tag'], name='idx_ct_tag'), models.Index(fields=['content_item'], name='idx_ct_item')],
                'unique_together': {('content_item', 'tag')},
            },
        ),
    ]
